namespace Proyecto_Gregory
{
    partial class Form1
    {
        /// <summary>
        /// Variable del diseñador necesaria.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Limpiar los recursos que se estén usando.
        /// </summary>
        /// <param name="disposing">true si los recursos administrados se deben desechar; false en caso contrario.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Código generado por el Diseñador de Windows Forms

        /// <summary>
        /// Método necesario para admitir el Diseñador. No se puede modificar
        /// el contenido de este método con el editor de código.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form1));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges19 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges20 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges21 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges22 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges23 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges24 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges25 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges26 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges borderEdges27 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderEdges();
            this.panel1 = new System.Windows.Forms.Panel();
            this.labelhora = new System.Windows.Forms.Label();
            this.bunifuPictureBox2 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.labeluser = new System.Windows.Forms.Label();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.bunifuFormControlBox1 = new Bunifu.UI.WinForms.BunifuFormControlBox();
            this.label1 = new System.Windows.Forms.Label();
            this.paneluser = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.label6 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.bunifuButton21 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.panelfecha = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.label3 = new System.Windows.Forms.Label();
            this.fecha = new System.Windows.Forms.Label();
            this.panelmenu = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.btncerrar = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnsettings = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnfacturacion = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnreservaciones = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnhabitaciones = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnclientes = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btninicio = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.btnmenu = new Bunifu.UI.WinForms.BunifuButton.BunifuButton2();
            this.panel3 = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.panel2 = new System.Windows.Forms.Panel();
            this.paneldesktop = new System.Windows.Forms.Panel();
            this.panel4 = new System.Windows.Forms.Panel();
            this.descriptionpage = new System.Windows.Forms.Label();
            this.tittlepage = new System.Windows.Forms.Label();
            this.panel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            this.paneluser.SuspendLayout();
            this.panelfecha.SuspendLayout();
            this.panelmenu.SuspendLayout();
            this.panel4.SuspendLayout();
            this.SuspendLayout();
            // 
            // panel1
            // 
            this.panel1.Controls.Add(this.labelhora);
            this.panel1.Controls.Add(this.bunifuPictureBox2);
            this.panel1.Controls.Add(this.labeluser);
            this.panel1.Controls.Add(this.bunifuPictureBox1);
            this.panel1.Controls.Add(this.bunifuFormControlBox1);
            this.panel1.Controls.Add(this.label1);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(1200, 50);
            this.panel1.TabIndex = 1;
            this.panel1.MouseDown += new System.Windows.Forms.MouseEventHandler(this.panel1_MouseDown);
            // 
            // labelhora
            // 
            this.labelhora.AutoSize = true;
            this.labelhora.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.labelhora.ForeColor = System.Drawing.SystemColors.ControlDark;
            this.labelhora.Location = new System.Drawing.Point(947, 17);
            this.labelhora.Name = "labelhora";
            this.labelhora.Size = new System.Drawing.Size(41, 16);
            this.labelhora.TabIndex = 9;
            this.labelhora.Text = "00: 00";
            this.labelhora.MouseEnter += new System.EventHandler(this.labelhora_MouseEnter);
            this.labelhora.MouseLeave += new System.EventHandler(this.labelhora_MouseLeave);
            // 
            // bunifuPictureBox2
            // 
            this.bunifuPictureBox2.AllowFocused = false;
            this.bunifuPictureBox2.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox2.AutoSizeHeight = true;
            this.bunifuPictureBox2.BorderRadius = 9;
            this.bunifuPictureBox2.Image = ((System.Drawing.Image)(resources.GetObject("bunifuPictureBox2.Image")));
            this.bunifuPictureBox2.IsCircle = true;
            this.bunifuPictureBox2.Location = new System.Drawing.Point(923, 16);
            this.bunifuPictureBox2.Name = "bunifuPictureBox2";
            this.bunifuPictureBox2.Size = new System.Drawing.Size(18, 18);
            this.bunifuPictureBox2.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox2.TabIndex = 8;
            this.bunifuPictureBox2.TabStop = false;
            this.bunifuPictureBox2.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // labeluser
            // 
            this.labeluser.AutoSize = true;
            this.labeluser.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.labeluser.ForeColor = System.Drawing.SystemColors.ControlDark;
            this.labeluser.Location = new System.Drawing.Point(657, 16);
            this.labeluser.Name = "labeluser";
            this.labeluser.Size = new System.Drawing.Size(32, 16);
            this.labeluser.TabIndex = 7;
            this.labeluser.Text = "User";
            this.labeluser.Click += new System.EventHandler(this.labeluser_Click);
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox1.AutoSizeHeight = true;
            this.bunifuPictureBox1.BorderRadius = 13;
            this.bunifuPictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuPictureBox1.Image")));
            this.bunifuPictureBox1.IsCircle = true;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(624, 11);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(27, 27);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 6;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            // 
            // bunifuFormControlBox1
            // 
            this.bunifuFormControlBox1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuFormControlBox1.BunifuFormDrag = null;
            this.bunifuFormControlBox1.CloseBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.CloseBoxOptions.BorderRadius = 25;
            this.bunifuFormControlBox1.CloseBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.CloseBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.CloseBoxOptions.HoverColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(17)))), ((int)(((byte)(35)))));
            this.bunifuFormControlBox1.CloseBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.CloseBoxOptions.Icon")));
            this.bunifuFormControlBox1.CloseBoxOptions.IconAlt = null;
            this.bunifuFormControlBox1.CloseBoxOptions.IconColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.CloseBoxOptions.IconHoverColor = System.Drawing.Color.White;
            this.bunifuFormControlBox1.CloseBoxOptions.IconPressedColor = System.Drawing.Color.White;
            this.bunifuFormControlBox1.CloseBoxOptions.IconSize = new System.Drawing.Size(18, 18);
            this.bunifuFormControlBox1.CloseBoxOptions.PressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(17)))), ((int)(((byte)(35)))));
            this.bunifuFormControlBox1.HelpBox = false;
            this.bunifuFormControlBox1.HelpBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.HelpBoxOptions.BorderRadius = 0;
            this.bunifuFormControlBox1.HelpBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.HelpBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.HelpBoxOptions.HoverColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.HelpBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.HelpBoxOptions.Icon")));
            this.bunifuFormControlBox1.HelpBoxOptions.IconAlt = null;
            this.bunifuFormControlBox1.HelpBoxOptions.IconColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.HelpBoxOptions.IconHoverColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.HelpBoxOptions.IconPressedColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.HelpBoxOptions.IconSize = new System.Drawing.Size(22, 22);
            this.bunifuFormControlBox1.HelpBoxOptions.PressedColor = System.Drawing.Color.Silver;
            this.bunifuFormControlBox1.Location = new System.Drawing.Point(1139, 5);
            this.bunifuFormControlBox1.Margin = new System.Windows.Forms.Padding(2, 2, 2, 2);
            this.bunifuFormControlBox1.MaximizeBox = false;
            this.bunifuFormControlBox1.MaximizeBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.MaximizeBoxOptions.BorderRadius = 0;
            this.bunifuFormControlBox1.MaximizeBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.MaximizeBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.MaximizeBoxOptions.HoverColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.MaximizeBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.MaximizeBoxOptions.Icon")));
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconAlt = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.MaximizeBoxOptions.IconAlt")));
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconHoverColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconPressedColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconSize = new System.Drawing.Size(16, 16);
            this.bunifuFormControlBox1.MaximizeBoxOptions.PressedColor = System.Drawing.Color.Silver;
            this.bunifuFormControlBox1.MinimizeBox = false;
            this.bunifuFormControlBox1.MinimizeBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.MinimizeBoxOptions.BorderRadius = 0;
            this.bunifuFormControlBox1.MinimizeBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.MinimizeBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.MinimizeBoxOptions.HoverColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.MinimizeBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.MinimizeBoxOptions.Icon")));
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconAlt = null;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconHoverColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconPressedColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconSize = new System.Drawing.Size(14, 14);
            this.bunifuFormControlBox1.MinimizeBoxOptions.PressedColor = System.Drawing.Color.Silver;
            this.bunifuFormControlBox1.Name = "bunifuFormControlBox1";
            this.bunifuFormControlBox1.ShowDesignBorders = false;
            this.bunifuFormControlBox1.Size = new System.Drawing.Size(50, 40);
            this.bunifuFormControlBox1.TabIndex = 3;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.SystemColors.ControlDark;
            this.label1.Location = new System.Drawing.Point(20, 20);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(80, 16);
            this.label1.TabIndex = 4;
            this.label1.Text = "GestFinance";
            this.label1.MouseDown += new System.Windows.Forms.MouseEventHandler(this.panel1_MouseDown);
            // 
            // paneluser
            // 
            this.paneluser.BackColor = System.Drawing.Color.Transparent;
            this.paneluser.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("paneluser.BackgroundImage")));
            this.paneluser.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.paneluser.BorderRadius = 35;
            this.paneluser.Controls.Add(this.label6);
            this.paneluser.Controls.Add(this.label5);
            this.paneluser.Controls.Add(this.label4);
            this.paneluser.Controls.Add(this.label2);
            this.paneluser.Controls.Add(this.bunifuButton21);
            this.paneluser.GradientBottomLeft = System.Drawing.Color.White;
            this.paneluser.GradientBottomRight = System.Drawing.Color.White;
            this.paneluser.GradientTopLeft = System.Drawing.Color.White;
            this.paneluser.GradientTopRight = System.Drawing.Color.White;
            this.paneluser.Location = new System.Drawing.Point(548, 44);
            this.paneluser.Name = "paneluser";
            this.paneluser.Quality = 10;
            this.paneluser.Size = new System.Drawing.Size(250, 125);
            this.paneluser.TabIndex = 3;
            this.paneluser.Visible = false;
            this.paneluser.MouseEnter += new System.EventHandler(this.paneluser_MouseEnter);
            this.paneluser.MouseLeave += new System.EventHandler(this.paneluser_MouseLeave);
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label6.Location = new System.Drawing.Point(109, 51);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(45, 17);
            this.label6.TabIndex = 4;
            this.label6.Text = "admin";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.Location = new System.Drawing.Point(109, 23);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(45, 17);
            this.label5.TabIndex = 3;
            this.label5.Text = "admin";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold);
            this.label4.Location = new System.Drawing.Point(45, 52);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(56, 16);
            this.label4.TabIndex = 2;
            this.label4.Text = "Permiso:";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Century Gothic", 9F, System.Drawing.FontStyle.Bold);
            this.label2.Location = new System.Drawing.Point(48, 24);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(53, 16);
            this.label2.TabIndex = 1;
            this.label2.Text = "Usuario:";
            // 
            // bunifuButton21
            // 
            this.bunifuButton21.AllowAnimations = true;
            this.bunifuButton21.AllowMouseEffects = true;
            this.bunifuButton21.AllowToggling = false;
            this.bunifuButton21.AnimationSpeed = 200;
            this.bunifuButton21.AutoGenerateColors = false;
            this.bunifuButton21.AutoRoundBorders = false;
            this.bunifuButton21.AutoSizeLeftIcon = true;
            this.bunifuButton21.AutoSizeRightIcon = true;
            this.bunifuButton21.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton21.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.bunifuButton21.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton21.BackgroundImage")));
            this.bunifuButton21.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.ButtonText = "Editar usuario";
            this.bunifuButton21.ButtonTextMarginLeft = 0;
            this.bunifuButton21.ColorContrastOnClick = 45;
            this.bunifuButton21.ColorContrastOnHover = 45;
            this.bunifuButton21.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges19.BottomLeft = true;
            borderEdges19.BottomRight = true;
            borderEdges19.TopLeft = true;
            borderEdges19.TopRight = true;
            this.bunifuButton21.CustomizableEdges = borderEdges19;
            this.bunifuButton21.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton21.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton21.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton21.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton21.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.bunifuButton21.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.bunifuButton21.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton21.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton21.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton21.IconMarginLeft = 11;
            this.bunifuButton21.IconPadding = 10;
            this.bunifuButton21.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton21.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton21.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton21.IconSize = 25;
            this.bunifuButton21.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton21.IdleBorderRadius = 25;
            this.bunifuButton21.IdleBorderThickness = 1;
            this.bunifuButton21.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton21.IdleIconLeftImage = null;
            this.bunifuButton21.IdleIconRightImage = null;
            this.bunifuButton21.IndicateFocus = false;
            this.bunifuButton21.Location = new System.Drawing.Point(48, 83);
            this.bunifuButton21.Name = "bunifuButton21";
            this.bunifuButton21.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton21.OnDisabledState.BorderRadius = 25;
            this.bunifuButton21.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnDisabledState.BorderThickness = 1;
            this.bunifuButton21.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton21.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton21.OnDisabledState.IconLeftImage = null;
            this.bunifuButton21.OnDisabledState.IconRightImage = null;
            this.bunifuButton21.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton21.onHoverState.BorderRadius = 25;
            this.bunifuButton21.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.onHoverState.BorderThickness = 1;
            this.bunifuButton21.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton21.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.onHoverState.IconLeftImage = null;
            this.bunifuButton21.onHoverState.IconRightImage = null;
            this.bunifuButton21.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton21.OnIdleState.BorderRadius = 25;
            this.bunifuButton21.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnIdleState.BorderThickness = 1;
            this.bunifuButton21.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.bunifuButton21.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.OnIdleState.IconLeftImage = null;
            this.bunifuButton21.OnIdleState.IconRightImage = null;
            this.bunifuButton21.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton21.OnPressedState.BorderRadius = 25;
            this.bunifuButton21.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.bunifuButton21.OnPressedState.BorderThickness = 1;
            this.bunifuButton21.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton21.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton21.OnPressedState.IconLeftImage = null;
            this.bunifuButton21.OnPressedState.IconRightImage = null;
            this.bunifuButton21.Size = new System.Drawing.Size(150, 30);
            this.bunifuButton21.TabIndex = 0;
            this.bunifuButton21.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton21.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton21.TextMarginLeft = 0;
            this.bunifuButton21.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton21.UseDefaultRadiusAndThickness = true;
            this.bunifuButton21.MouseEnter += new System.EventHandler(this.paneluser_MouseEnter);
            // 
            // panelfecha
            // 
            this.panelfecha.BackColor = System.Drawing.Color.Transparent;
            this.panelfecha.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("panelfecha.BackgroundImage")));
            this.panelfecha.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.panelfecha.BorderRadius = 35;
            this.panelfecha.Controls.Add(this.label3);
            this.panelfecha.Controls.Add(this.fecha);
            this.panelfecha.GradientBottomLeft = System.Drawing.Color.White;
            this.panelfecha.GradientBottomRight = System.Drawing.Color.White;
            this.panelfecha.GradientTopLeft = System.Drawing.Color.White;
            this.panelfecha.GradientTopRight = System.Drawing.Color.White;
            this.panelfecha.Location = new System.Drawing.Point(866, 44);
            this.panelfecha.Name = "panelfecha";
            this.panelfecha.Quality = 10;
            this.panelfecha.Size = new System.Drawing.Size(200, 90);
            this.panelfecha.TabIndex = 4;
            this.panelfecha.Visible = false;
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.BackColor = System.Drawing.Color.Transparent;
            this.label3.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.ForeColor = System.Drawing.Color.Black;
            this.label3.Location = new System.Drawing.Point(41, 20);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(112, 19);
            this.label3.TabIndex = 6;
            this.label3.Text = "Fecha y Hora";
            // 
            // fecha
            // 
            this.fecha.AutoSize = true;
            this.fecha.BackColor = System.Drawing.Color.Transparent;
            this.fecha.Font = new System.Drawing.Font("Century Gothic", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.fecha.ForeColor = System.Drawing.Color.DarkGray;
            this.fecha.Location = new System.Drawing.Point(21, 48);
            this.fecha.Name = "fecha";
            this.fecha.Size = new System.Drawing.Size(161, 19);
            this.fecha.TabIndex = 5;
            this.fecha.Text = "09/08/2023 04:23:53";
            // 
            // panelmenu
            // 
            this.panelmenu.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.panelmenu.BackColor = System.Drawing.Color.Transparent;
            this.panelmenu.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("panelmenu.BackgroundImage")));
            this.panelmenu.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.panelmenu.BorderRadius = 35;
            this.panelmenu.Controls.Add(this.btncerrar);
            this.panelmenu.Controls.Add(this.btnsettings);
            this.panelmenu.Controls.Add(this.btnfacturacion);
            this.panelmenu.Controls.Add(this.btnreservaciones);
            this.panelmenu.Controls.Add(this.btnhabitaciones);
            this.panelmenu.Controls.Add(this.btnclientes);
            this.panelmenu.Controls.Add(this.btninicio);
            this.panelmenu.Controls.Add(this.btnmenu);
            this.panelmenu.Controls.Add(this.panel3);
            this.panelmenu.GradientBottomLeft = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(54)))));
            this.panelmenu.GradientBottomRight = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(54)))));
            this.panelmenu.GradientTopLeft = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(54)))));
            this.panelmenu.GradientTopRight = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(54)))));
            this.panelmenu.Location = new System.Drawing.Point(50, 69);
            this.panelmenu.Name = "panelmenu";
            this.panelmenu.Padding = new System.Windows.Forms.Padding(5, 15, 5, 15);
            this.panelmenu.Quality = 10;
            this.panelmenu.Size = new System.Drawing.Size(190, 450);
            this.panelmenu.TabIndex = 0;
            // 
            // btncerrar
            // 
            this.btncerrar.AllowAnimations = true;
            this.btncerrar.AllowMouseEffects = true;
            this.btncerrar.AllowToggling = false;
            this.btncerrar.AnimationSpeed = 200;
            this.btncerrar.AutoGenerateColors = false;
            this.btncerrar.AutoRoundBorders = false;
            this.btncerrar.AutoSizeLeftIcon = true;
            this.btncerrar.AutoSizeRightIcon = true;
            this.btncerrar.BackColor = System.Drawing.Color.Transparent;
            this.btncerrar.BackColor1 = System.Drawing.Color.Transparent;
            this.btncerrar.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btncerrar.BackgroundImage")));
            this.btncerrar.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btncerrar.ButtonText = "Cerrar Sesion";
            this.btncerrar.ButtonTextMarginLeft = 0;
            this.btncerrar.ColorContrastOnClick = 45;
            this.btncerrar.ColorContrastOnHover = 45;
            this.btncerrar.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges20.BottomLeft = true;
            borderEdges20.BottomRight = true;
            borderEdges20.TopLeft = true;
            borderEdges20.TopRight = true;
            this.btncerrar.CustomizableEdges = borderEdges20;
            this.btncerrar.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btncerrar.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btncerrar.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btncerrar.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btncerrar.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.btncerrar.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btncerrar.Font = new System.Drawing.Font("Century Gothic", 10F, System.Drawing.FontStyle.Bold);
            this.btncerrar.ForeColor = System.Drawing.Color.White;
            this.btncerrar.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btncerrar.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btncerrar.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btncerrar.IconMarginLeft = 11;
            this.btncerrar.IconPadding = 10;
            this.btncerrar.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btncerrar.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btncerrar.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btncerrar.IconSize = 25;
            this.btncerrar.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btncerrar.IdleBorderRadius = 25;
            this.btncerrar.IdleBorderThickness = 1;
            this.btncerrar.IdleFillColor = System.Drawing.Color.Transparent;
            this.btncerrar.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btncerrar.IdleIconLeftImage")));
            this.btncerrar.IdleIconRightImage = null;
            this.btncerrar.IndicateFocus = false;
            this.btncerrar.Location = new System.Drawing.Point(5, 395);
            this.btncerrar.Name = "btncerrar";
            this.btncerrar.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btncerrar.OnDisabledState.BorderRadius = 25;
            this.btncerrar.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btncerrar.OnDisabledState.BorderThickness = 1;
            this.btncerrar.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btncerrar.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btncerrar.OnDisabledState.IconLeftImage = null;
            this.btncerrar.OnDisabledState.IconRightImage = null;
            this.btncerrar.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btncerrar.onHoverState.BorderRadius = 25;
            this.btncerrar.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btncerrar.onHoverState.BorderThickness = 1;
            this.btncerrar.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btncerrar.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btncerrar.onHoverState.IconLeftImage = null;
            this.btncerrar.onHoverState.IconRightImage = null;
            this.btncerrar.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btncerrar.OnIdleState.BorderRadius = 25;
            this.btncerrar.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btncerrar.OnIdleState.BorderThickness = 1;
            this.btncerrar.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btncerrar.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btncerrar.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btncerrar.OnIdleState.IconLeftImage")));
            this.btncerrar.OnIdleState.IconRightImage = null;
            this.btncerrar.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btncerrar.OnPressedState.BorderRadius = 25;
            this.btncerrar.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btncerrar.OnPressedState.BorderThickness = 1;
            this.btncerrar.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btncerrar.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btncerrar.OnPressedState.IconLeftImage = null;
            this.btncerrar.OnPressedState.IconRightImage = null;
            this.btncerrar.Size = new System.Drawing.Size(180, 40);
            this.btncerrar.TabIndex = 11;
            this.btncerrar.Tag = "Cerrar Sesion";
            this.btncerrar.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btncerrar.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btncerrar.TextMarginLeft = 0;
            this.btncerrar.TextPadding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.btncerrar.UseDefaultRadiusAndThickness = true;
            // 
            // btnsettings
            // 
            this.btnsettings.AllowAnimations = true;
            this.btnsettings.AllowMouseEffects = true;
            this.btnsettings.AllowToggling = false;
            this.btnsettings.AnimationSpeed = 200;
            this.btnsettings.AutoGenerateColors = false;
            this.btnsettings.AutoRoundBorders = false;
            this.btnsettings.AutoSizeLeftIcon = true;
            this.btnsettings.AutoSizeRightIcon = true;
            this.btnsettings.BackColor = System.Drawing.Color.Transparent;
            this.btnsettings.BackColor1 = System.Drawing.Color.Transparent;
            this.btnsettings.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnsettings.BackgroundImage")));
            this.btnsettings.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnsettings.ButtonText = "Configuracion";
            this.btnsettings.ButtonTextMarginLeft = 0;
            this.btnsettings.ColorContrastOnClick = 45;
            this.btnsettings.ColorContrastOnHover = 45;
            this.btnsettings.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges21.BottomLeft = true;
            borderEdges21.BottomRight = true;
            borderEdges21.TopLeft = true;
            borderEdges21.TopRight = true;
            this.btnsettings.CustomizableEdges = borderEdges21;
            this.btnsettings.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnsettings.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnsettings.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnsettings.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnsettings.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnsettings.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnsettings.Font = new System.Drawing.Font("Century Gothic", 10F, System.Drawing.FontStyle.Bold);
            this.btnsettings.ForeColor = System.Drawing.Color.White;
            this.btnsettings.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnsettings.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnsettings.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnsettings.IconMarginLeft = 11;
            this.btnsettings.IconPadding = 10;
            this.btnsettings.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnsettings.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnsettings.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnsettings.IconSize = 25;
            this.btnsettings.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnsettings.IdleBorderRadius = 25;
            this.btnsettings.IdleBorderThickness = 1;
            this.btnsettings.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnsettings.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnsettings.IdleIconLeftImage")));
            this.btnsettings.IdleIconRightImage = null;
            this.btnsettings.IndicateFocus = false;
            this.btnsettings.Location = new System.Drawing.Point(5, 303);
            this.btnsettings.Name = "btnsettings";
            this.btnsettings.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnsettings.OnDisabledState.BorderRadius = 25;
            this.btnsettings.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnsettings.OnDisabledState.BorderThickness = 1;
            this.btnsettings.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnsettings.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnsettings.OnDisabledState.IconLeftImage = null;
            this.btnsettings.OnDisabledState.IconRightImage = null;
            this.btnsettings.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnsettings.onHoverState.BorderRadius = 25;
            this.btnsettings.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnsettings.onHoverState.BorderThickness = 1;
            this.btnsettings.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnsettings.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnsettings.onHoverState.IconLeftImage = null;
            this.btnsettings.onHoverState.IconRightImage = null;
            this.btnsettings.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnsettings.OnIdleState.BorderRadius = 25;
            this.btnsettings.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnsettings.OnIdleState.BorderThickness = 1;
            this.btnsettings.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnsettings.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnsettings.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnsettings.OnIdleState.IconLeftImage")));
            this.btnsettings.OnIdleState.IconRightImage = null;
            this.btnsettings.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnsettings.OnPressedState.BorderRadius = 25;
            this.btnsettings.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnsettings.OnPressedState.BorderThickness = 1;
            this.btnsettings.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnsettings.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnsettings.OnPressedState.IconLeftImage = null;
            this.btnsettings.OnPressedState.IconRightImage = null;
            this.btnsettings.Size = new System.Drawing.Size(180, 40);
            this.btnsettings.TabIndex = 10;
            this.btnsettings.Tag = "Configuracion";
            this.btnsettings.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnsettings.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnsettings.TextMarginLeft = 0;
            this.btnsettings.TextPadding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.btnsettings.UseDefaultRadiusAndThickness = true;
            // 
            // btnfacturacion
            // 
            this.btnfacturacion.AllowAnimations = true;
            this.btnfacturacion.AllowMouseEffects = true;
            this.btnfacturacion.AllowToggling = false;
            this.btnfacturacion.AnimationSpeed = 200;
            this.btnfacturacion.AutoGenerateColors = false;
            this.btnfacturacion.AutoRoundBorders = false;
            this.btnfacturacion.AutoSizeLeftIcon = true;
            this.btnfacturacion.AutoSizeRightIcon = true;
            this.btnfacturacion.BackColor = System.Drawing.Color.Transparent;
            this.btnfacturacion.BackColor1 = System.Drawing.Color.Transparent;
            this.btnfacturacion.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnfacturacion.BackgroundImage")));
            this.btnfacturacion.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnfacturacion.ButtonText = "Facturacion";
            this.btnfacturacion.ButtonTextMarginLeft = 0;
            this.btnfacturacion.ColorContrastOnClick = 45;
            this.btnfacturacion.ColorContrastOnHover = 45;
            this.btnfacturacion.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges22.BottomLeft = true;
            borderEdges22.BottomRight = true;
            borderEdges22.TopLeft = true;
            borderEdges22.TopRight = true;
            this.btnfacturacion.CustomizableEdges = borderEdges22;
            this.btnfacturacion.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnfacturacion.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnfacturacion.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnfacturacion.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnfacturacion.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnfacturacion.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnfacturacion.Font = new System.Drawing.Font("Century Gothic", 10F, System.Drawing.FontStyle.Bold);
            this.btnfacturacion.ForeColor = System.Drawing.Color.White;
            this.btnfacturacion.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnfacturacion.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnfacturacion.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnfacturacion.IconMarginLeft = 11;
            this.btnfacturacion.IconPadding = 10;
            this.btnfacturacion.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnfacturacion.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnfacturacion.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnfacturacion.IconSize = 25;
            this.btnfacturacion.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnfacturacion.IdleBorderRadius = 25;
            this.btnfacturacion.IdleBorderThickness = 1;
            this.btnfacturacion.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnfacturacion.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnfacturacion.IdleIconLeftImage")));
            this.btnfacturacion.IdleIconRightImage = null;
            this.btnfacturacion.IndicateFocus = false;
            this.btnfacturacion.Location = new System.Drawing.Point(5, 263);
            this.btnfacturacion.Name = "btnfacturacion";
            this.btnfacturacion.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnfacturacion.OnDisabledState.BorderRadius = 25;
            this.btnfacturacion.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnfacturacion.OnDisabledState.BorderThickness = 1;
            this.btnfacturacion.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnfacturacion.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnfacturacion.OnDisabledState.IconLeftImage = null;
            this.btnfacturacion.OnDisabledState.IconRightImage = null;
            this.btnfacturacion.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnfacturacion.onHoverState.BorderRadius = 25;
            this.btnfacturacion.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnfacturacion.onHoverState.BorderThickness = 1;
            this.btnfacturacion.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnfacturacion.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnfacturacion.onHoverState.IconLeftImage = null;
            this.btnfacturacion.onHoverState.IconRightImage = null;
            this.btnfacturacion.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnfacturacion.OnIdleState.BorderRadius = 25;
            this.btnfacturacion.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnfacturacion.OnIdleState.BorderThickness = 1;
            this.btnfacturacion.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnfacturacion.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnfacturacion.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnfacturacion.OnIdleState.IconLeftImage")));
            this.btnfacturacion.OnIdleState.IconRightImage = null;
            this.btnfacturacion.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnfacturacion.OnPressedState.BorderRadius = 25;
            this.btnfacturacion.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnfacturacion.OnPressedState.BorderThickness = 1;
            this.btnfacturacion.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnfacturacion.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnfacturacion.OnPressedState.IconLeftImage = null;
            this.btnfacturacion.OnPressedState.IconRightImage = null;
            this.btnfacturacion.Size = new System.Drawing.Size(180, 40);
            this.btnfacturacion.TabIndex = 9;
            this.btnfacturacion.Tag = "Facturacion";
            this.btnfacturacion.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnfacturacion.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnfacturacion.TextMarginLeft = 0;
            this.btnfacturacion.TextPadding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.btnfacturacion.UseDefaultRadiusAndThickness = true;
            // 
            // btnreservaciones
            // 
            this.btnreservaciones.AllowAnimations = true;
            this.btnreservaciones.AllowMouseEffects = true;
            this.btnreservaciones.AllowToggling = false;
            this.btnreservaciones.AnimationSpeed = 200;
            this.btnreservaciones.AutoGenerateColors = false;
            this.btnreservaciones.AutoRoundBorders = false;
            this.btnreservaciones.AutoSizeLeftIcon = true;
            this.btnreservaciones.AutoSizeRightIcon = true;
            this.btnreservaciones.BackColor = System.Drawing.Color.Transparent;
            this.btnreservaciones.BackColor1 = System.Drawing.Color.Transparent;
            this.btnreservaciones.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnreservaciones.BackgroundImage")));
            this.btnreservaciones.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnreservaciones.ButtonText = "Reservaciones";
            this.btnreservaciones.ButtonTextMarginLeft = 0;
            this.btnreservaciones.ColorContrastOnClick = 45;
            this.btnreservaciones.ColorContrastOnHover = 45;
            this.btnreservaciones.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges23.BottomLeft = true;
            borderEdges23.BottomRight = true;
            borderEdges23.TopLeft = true;
            borderEdges23.TopRight = true;
            this.btnreservaciones.CustomizableEdges = borderEdges23;
            this.btnreservaciones.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnreservaciones.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnreservaciones.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnreservaciones.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnreservaciones.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnreservaciones.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnreservaciones.Font = new System.Drawing.Font("Century Gothic", 10F, System.Drawing.FontStyle.Bold);
            this.btnreservaciones.ForeColor = System.Drawing.Color.White;
            this.btnreservaciones.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnreservaciones.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnreservaciones.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnreservaciones.IconMarginLeft = 11;
            this.btnreservaciones.IconPadding = 10;
            this.btnreservaciones.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnreservaciones.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnreservaciones.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnreservaciones.IconSize = 25;
            this.btnreservaciones.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnreservaciones.IdleBorderRadius = 25;
            this.btnreservaciones.IdleBorderThickness = 1;
            this.btnreservaciones.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnreservaciones.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnreservaciones.IdleIconLeftImage")));
            this.btnreservaciones.IdleIconRightImage = null;
            this.btnreservaciones.IndicateFocus = false;
            this.btnreservaciones.Location = new System.Drawing.Point(5, 223);
            this.btnreservaciones.Name = "btnreservaciones";
            this.btnreservaciones.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnreservaciones.OnDisabledState.BorderRadius = 25;
            this.btnreservaciones.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnreservaciones.OnDisabledState.BorderThickness = 1;
            this.btnreservaciones.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnreservaciones.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnreservaciones.OnDisabledState.IconLeftImage = null;
            this.btnreservaciones.OnDisabledState.IconRightImage = null;
            this.btnreservaciones.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnreservaciones.onHoverState.BorderRadius = 25;
            this.btnreservaciones.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnreservaciones.onHoverState.BorderThickness = 1;
            this.btnreservaciones.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnreservaciones.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnreservaciones.onHoverState.IconLeftImage = null;
            this.btnreservaciones.onHoverState.IconRightImage = null;
            this.btnreservaciones.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnreservaciones.OnIdleState.BorderRadius = 25;
            this.btnreservaciones.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnreservaciones.OnIdleState.BorderThickness = 1;
            this.btnreservaciones.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnreservaciones.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnreservaciones.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnreservaciones.OnIdleState.IconLeftImage")));
            this.btnreservaciones.OnIdleState.IconRightImage = null;
            this.btnreservaciones.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnreservaciones.OnPressedState.BorderRadius = 25;
            this.btnreservaciones.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnreservaciones.OnPressedState.BorderThickness = 1;
            this.btnreservaciones.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnreservaciones.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnreservaciones.OnPressedState.IconLeftImage = null;
            this.btnreservaciones.OnPressedState.IconRightImage = null;
            this.btnreservaciones.Size = new System.Drawing.Size(180, 40);
            this.btnreservaciones.TabIndex = 8;
            this.btnreservaciones.Tag = "Reservaciones";
            this.btnreservaciones.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnreservaciones.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnreservaciones.TextMarginLeft = 0;
            this.btnreservaciones.TextPadding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.btnreservaciones.UseDefaultRadiusAndThickness = true;
            // 
            // btnhabitaciones
            // 
            this.btnhabitaciones.AllowAnimations = true;
            this.btnhabitaciones.AllowMouseEffects = true;
            this.btnhabitaciones.AllowToggling = false;
            this.btnhabitaciones.AnimationSpeed = 200;
            this.btnhabitaciones.AutoGenerateColors = false;
            this.btnhabitaciones.AutoRoundBorders = false;
            this.btnhabitaciones.AutoSizeLeftIcon = true;
            this.btnhabitaciones.AutoSizeRightIcon = true;
            this.btnhabitaciones.BackColor = System.Drawing.Color.Transparent;
            this.btnhabitaciones.BackColor1 = System.Drawing.Color.Transparent;
            this.btnhabitaciones.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnhabitaciones.BackgroundImage")));
            this.btnhabitaciones.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnhabitaciones.ButtonText = "Habitaciones";
            this.btnhabitaciones.ButtonTextMarginLeft = 0;
            this.btnhabitaciones.ColorContrastOnClick = 45;
            this.btnhabitaciones.ColorContrastOnHover = 45;
            this.btnhabitaciones.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges24.BottomLeft = true;
            borderEdges24.BottomRight = true;
            borderEdges24.TopLeft = true;
            borderEdges24.TopRight = true;
            this.btnhabitaciones.CustomizableEdges = borderEdges24;
            this.btnhabitaciones.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnhabitaciones.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnhabitaciones.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnhabitaciones.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnhabitaciones.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnhabitaciones.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnhabitaciones.Font = new System.Drawing.Font("Century Gothic", 10F, System.Drawing.FontStyle.Bold);
            this.btnhabitaciones.ForeColor = System.Drawing.Color.White;
            this.btnhabitaciones.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnhabitaciones.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnhabitaciones.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnhabitaciones.IconMarginLeft = 11;
            this.btnhabitaciones.IconPadding = 10;
            this.btnhabitaciones.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnhabitaciones.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnhabitaciones.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnhabitaciones.IconSize = 25;
            this.btnhabitaciones.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnhabitaciones.IdleBorderRadius = 25;
            this.btnhabitaciones.IdleBorderThickness = 1;
            this.btnhabitaciones.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnhabitaciones.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnhabitaciones.IdleIconLeftImage")));
            this.btnhabitaciones.IdleIconRightImage = null;
            this.btnhabitaciones.IndicateFocus = false;
            this.btnhabitaciones.Location = new System.Drawing.Point(5, 183);
            this.btnhabitaciones.Name = "btnhabitaciones";
            this.btnhabitaciones.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnhabitaciones.OnDisabledState.BorderRadius = 25;
            this.btnhabitaciones.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnhabitaciones.OnDisabledState.BorderThickness = 1;
            this.btnhabitaciones.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnhabitaciones.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnhabitaciones.OnDisabledState.IconLeftImage = null;
            this.btnhabitaciones.OnDisabledState.IconRightImage = null;
            this.btnhabitaciones.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnhabitaciones.onHoverState.BorderRadius = 25;
            this.btnhabitaciones.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnhabitaciones.onHoverState.BorderThickness = 1;
            this.btnhabitaciones.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnhabitaciones.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnhabitaciones.onHoverState.IconLeftImage = null;
            this.btnhabitaciones.onHoverState.IconRightImage = null;
            this.btnhabitaciones.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnhabitaciones.OnIdleState.BorderRadius = 25;
            this.btnhabitaciones.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnhabitaciones.OnIdleState.BorderThickness = 1;
            this.btnhabitaciones.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnhabitaciones.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnhabitaciones.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnhabitaciones.OnIdleState.IconLeftImage")));
            this.btnhabitaciones.OnIdleState.IconRightImage = null;
            this.btnhabitaciones.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnhabitaciones.OnPressedState.BorderRadius = 25;
            this.btnhabitaciones.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnhabitaciones.OnPressedState.BorderThickness = 1;
            this.btnhabitaciones.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnhabitaciones.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnhabitaciones.OnPressedState.IconLeftImage = null;
            this.btnhabitaciones.OnPressedState.IconRightImage = null;
            this.btnhabitaciones.Size = new System.Drawing.Size(180, 40);
            this.btnhabitaciones.TabIndex = 7;
            this.btnhabitaciones.Tag = "Habitaciones";
            this.btnhabitaciones.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnhabitaciones.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnhabitaciones.TextMarginLeft = 0;
            this.btnhabitaciones.TextPadding = new System.Windows.Forms.Padding(10, 0, 0, 0);
            this.btnhabitaciones.UseDefaultRadiusAndThickness = true;
            this.btnhabitaciones.Click += new System.EventHandler(this.btnhabitaciones_Click);
            // 
            // btnclientes
            // 
            this.btnclientes.AllowAnimations = true;
            this.btnclientes.AllowMouseEffects = true;
            this.btnclientes.AllowToggling = false;
            this.btnclientes.AnimationSpeed = 200;
            this.btnclientes.AutoGenerateColors = false;
            this.btnclientes.AutoRoundBorders = false;
            this.btnclientes.AutoSizeLeftIcon = true;
            this.btnclientes.AutoSizeRightIcon = true;
            this.btnclientes.BackColor = System.Drawing.Color.Transparent;
            this.btnclientes.BackColor1 = System.Drawing.Color.Transparent;
            this.btnclientes.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnclientes.BackgroundImage")));
            this.btnclientes.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnclientes.ButtonText = "Clientes";
            this.btnclientes.ButtonTextMarginLeft = 0;
            this.btnclientes.ColorContrastOnClick = 45;
            this.btnclientes.ColorContrastOnHover = 45;
            this.btnclientes.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges25.BottomLeft = true;
            borderEdges25.BottomRight = true;
            borderEdges25.TopLeft = true;
            borderEdges25.TopRight = true;
            this.btnclientes.CustomizableEdges = borderEdges25;
            this.btnclientes.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnclientes.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnclientes.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnclientes.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnclientes.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnclientes.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnclientes.Font = new System.Drawing.Font("Century Gothic", 10F, System.Drawing.FontStyle.Bold);
            this.btnclientes.ForeColor = System.Drawing.Color.White;
            this.btnclientes.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnclientes.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnclientes.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnclientes.IconMarginLeft = 11;
            this.btnclientes.IconPadding = 10;
            this.btnclientes.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnclientes.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnclientes.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnclientes.IconSize = 25;
            this.btnclientes.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnclientes.IdleBorderRadius = 25;
            this.btnclientes.IdleBorderThickness = 1;
            this.btnclientes.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnclientes.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnclientes.IdleIconLeftImage")));
            this.btnclientes.IdleIconRightImage = null;
            this.btnclientes.IndicateFocus = false;
            this.btnclientes.Location = new System.Drawing.Point(5, 143);
            this.btnclientes.Name = "btnclientes";
            this.btnclientes.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnclientes.OnDisabledState.BorderRadius = 25;
            this.btnclientes.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnclientes.OnDisabledState.BorderThickness = 1;
            this.btnclientes.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnclientes.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnclientes.OnDisabledState.IconLeftImage = null;
            this.btnclientes.OnDisabledState.IconRightImage = null;
            this.btnclientes.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnclientes.onHoverState.BorderRadius = 25;
            this.btnclientes.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnclientes.onHoverState.BorderThickness = 1;
            this.btnclientes.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnclientes.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnclientes.onHoverState.IconLeftImage = null;
            this.btnclientes.onHoverState.IconRightImage = null;
            this.btnclientes.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnclientes.OnIdleState.BorderRadius = 25;
            this.btnclientes.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnclientes.OnIdleState.BorderThickness = 1;
            this.btnclientes.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnclientes.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnclientes.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnclientes.OnIdleState.IconLeftImage")));
            this.btnclientes.OnIdleState.IconRightImage = null;
            this.btnclientes.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnclientes.OnPressedState.BorderRadius = 25;
            this.btnclientes.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnclientes.OnPressedState.BorderThickness = 1;
            this.btnclientes.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnclientes.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnclientes.OnPressedState.IconLeftImage = null;
            this.btnclientes.OnPressedState.IconRightImage = null;
            this.btnclientes.Size = new System.Drawing.Size(180, 40);
            this.btnclientes.TabIndex = 6;
            this.btnclientes.Tag = "Clientes";
            this.btnclientes.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnclientes.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnclientes.TextMarginLeft = 0;
            this.btnclientes.TextPadding = new System.Windows.Forms.Padding(5, 0, 0, 0);
            this.btnclientes.UseDefaultRadiusAndThickness = true;
            // 
            // btninicio
            // 
            this.btninicio.AllowAnimations = true;
            this.btninicio.AllowMouseEffects = true;
            this.btninicio.AllowToggling = false;
            this.btninicio.AnimationSpeed = 200;
            this.btninicio.AutoGenerateColors = false;
            this.btninicio.AutoRoundBorders = false;
            this.btninicio.AutoSizeLeftIcon = true;
            this.btninicio.AutoSizeRightIcon = true;
            this.btninicio.BackColor = System.Drawing.Color.Transparent;
            this.btninicio.BackColor1 = System.Drawing.Color.Transparent;
            this.btninicio.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btninicio.BackgroundImage")));
            this.btninicio.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btninicio.ButtonText = "Inicio";
            this.btninicio.ButtonTextMarginLeft = 0;
            this.btninicio.ColorContrastOnClick = 45;
            this.btninicio.ColorContrastOnHover = 45;
            this.btninicio.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges26.BottomLeft = true;
            borderEdges26.BottomRight = true;
            borderEdges26.TopLeft = true;
            borderEdges26.TopRight = true;
            this.btninicio.CustomizableEdges = borderEdges26;
            this.btninicio.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btninicio.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btninicio.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btninicio.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btninicio.Dock = System.Windows.Forms.DockStyle.Top;
            this.btninicio.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btninicio.Font = new System.Drawing.Font("Century Gothic", 10F, System.Drawing.FontStyle.Bold);
            this.btninicio.ForeColor = System.Drawing.Color.White;
            this.btninicio.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btninicio.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btninicio.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btninicio.IconMarginLeft = 11;
            this.btninicio.IconPadding = 10;
            this.btninicio.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btninicio.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btninicio.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btninicio.IconSize = 25;
            this.btninicio.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btninicio.IdleBorderRadius = 25;
            this.btninicio.IdleBorderThickness = 1;
            this.btninicio.IdleFillColor = System.Drawing.Color.Transparent;
            this.btninicio.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btninicio.IdleIconLeftImage")));
            this.btninicio.IdleIconRightImage = null;
            this.btninicio.IndicateFocus = false;
            this.btninicio.Location = new System.Drawing.Point(5, 102);
            this.btninicio.Name = "btninicio";
            this.btninicio.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btninicio.OnDisabledState.BorderRadius = 25;
            this.btninicio.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btninicio.OnDisabledState.BorderThickness = 1;
            this.btninicio.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btninicio.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btninicio.OnDisabledState.IconLeftImage = null;
            this.btninicio.OnDisabledState.IconRightImage = null;
            this.btninicio.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btninicio.onHoverState.BorderRadius = 25;
            this.btninicio.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btninicio.onHoverState.BorderThickness = 1;
            this.btninicio.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btninicio.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btninicio.onHoverState.IconLeftImage = null;
            this.btninicio.onHoverState.IconRightImage = null;
            this.btninicio.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btninicio.OnIdleState.BorderRadius = 25;
            this.btninicio.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btninicio.OnIdleState.BorderThickness = 1;
            this.btninicio.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btninicio.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btninicio.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btninicio.OnIdleState.IconLeftImage")));
            this.btninicio.OnIdleState.IconRightImage = null;
            this.btninicio.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btninicio.OnPressedState.BorderRadius = 25;
            this.btninicio.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btninicio.OnPressedState.BorderThickness = 1;
            this.btninicio.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btninicio.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btninicio.OnPressedState.IconLeftImage = null;
            this.btninicio.OnPressedState.IconRightImage = null;
            this.btninicio.Size = new System.Drawing.Size(180, 41);
            this.btninicio.TabIndex = 5;
            this.btninicio.Tag = "Inicio";
            this.btninicio.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btninicio.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btninicio.TextMarginLeft = 0;
            this.btninicio.TextPadding = new System.Windows.Forms.Padding(5, 0, 0, 0);
            this.btninicio.UseDefaultRadiusAndThickness = true;
            this.btninicio.Click += new System.EventHandler(this.btninicio_Click);
            // 
            // btnmenu
            // 
            this.btnmenu.AllowAnimations = true;
            this.btnmenu.AllowMouseEffects = true;
            this.btnmenu.AllowToggling = false;
            this.btnmenu.AnimationSpeed = 200;
            this.btnmenu.AutoGenerateColors = false;
            this.btnmenu.AutoRoundBorders = false;
            this.btnmenu.AutoSizeLeftIcon = true;
            this.btnmenu.AutoSizeRightIcon = true;
            this.btnmenu.BackColor = System.Drawing.Color.Transparent;
            this.btnmenu.BackColor1 = System.Drawing.Color.Transparent;
            this.btnmenu.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnmenu.BackgroundImage")));
            this.btnmenu.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnmenu.ButtonText = "";
            this.btnmenu.ButtonTextMarginLeft = 0;
            this.btnmenu.ColorContrastOnClick = 45;
            this.btnmenu.ColorContrastOnHover = 45;
            this.btnmenu.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges27.BottomLeft = true;
            borderEdges27.BottomRight = true;
            borderEdges27.TopLeft = true;
            borderEdges27.TopRight = true;
            this.btnmenu.CustomizableEdges = borderEdges27;
            this.btnmenu.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnmenu.DisabledBorderColor = System.Drawing.Color.Transparent;
            this.btnmenu.DisabledFillColor = System.Drawing.Color.Transparent;
            this.btnmenu.DisabledForecolor = System.Drawing.Color.Transparent;
            this.btnmenu.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.ButtonStates.Pressed;
            this.btnmenu.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnmenu.ForeColor = System.Drawing.Color.White;
            this.btnmenu.IconLeftAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnmenu.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnmenu.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnmenu.IconMarginLeft = 11;
            this.btnmenu.IconPadding = 10;
            this.btnmenu.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnmenu.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnmenu.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnmenu.IconSize = 25;
            this.btnmenu.IdleBorderColor = System.Drawing.Color.Transparent;
            this.btnmenu.IdleBorderRadius = 35;
            this.btnmenu.IdleBorderThickness = 1;
            this.btnmenu.IdleFillColor = System.Drawing.Color.Transparent;
            this.btnmenu.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnmenu.IdleIconLeftImage")));
            this.btnmenu.IdleIconRightImage = null;
            this.btnmenu.IndicateFocus = false;
            this.btnmenu.Location = new System.Drawing.Point(133, 13);
            this.btnmenu.Name = "btnmenu";
            this.btnmenu.OnDisabledState.BorderColor = System.Drawing.Color.Transparent;
            this.btnmenu.OnDisabledState.BorderRadius = 35;
            this.btnmenu.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnmenu.OnDisabledState.BorderThickness = 1;
            this.btnmenu.OnDisabledState.FillColor = System.Drawing.Color.Transparent;
            this.btnmenu.OnDisabledState.ForeColor = System.Drawing.Color.Transparent;
            this.btnmenu.OnDisabledState.IconLeftImage = null;
            this.btnmenu.OnDisabledState.IconRightImage = null;
            this.btnmenu.onHoverState.BorderColor = System.Drawing.Color.Transparent;
            this.btnmenu.onHoverState.BorderRadius = 35;
            this.btnmenu.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnmenu.onHoverState.BorderThickness = 1;
            this.btnmenu.onHoverState.FillColor = System.Drawing.Color.Transparent;
            this.btnmenu.onHoverState.ForeColor = System.Drawing.Color.Transparent;
            this.btnmenu.onHoverState.IconLeftImage = null;
            this.btnmenu.onHoverState.IconRightImage = null;
            this.btnmenu.OnIdleState.BorderColor = System.Drawing.Color.Transparent;
            this.btnmenu.OnIdleState.BorderRadius = 35;
            this.btnmenu.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnmenu.OnIdleState.BorderThickness = 1;
            this.btnmenu.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.btnmenu.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnmenu.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnmenu.OnIdleState.IconLeftImage")));
            this.btnmenu.OnIdleState.IconRightImage = null;
            this.btnmenu.OnPressedState.BorderColor = System.Drawing.Color.Transparent;
            this.btnmenu.OnPressedState.BorderRadius = 35;
            this.btnmenu.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton2.BorderStyles.Solid;
            this.btnmenu.OnPressedState.BorderThickness = 1;
            this.btnmenu.OnPressedState.FillColor = System.Drawing.Color.Transparent;
            this.btnmenu.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnmenu.OnPressedState.IconLeftImage = null;
            this.btnmenu.OnPressedState.IconRightImage = null;
            this.btnmenu.Size = new System.Drawing.Size(48, 48);
            this.btnmenu.TabIndex = 3;
            this.btnmenu.Tag = " ";
            this.btnmenu.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnmenu.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnmenu.TextMarginLeft = 0;
            this.btnmenu.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnmenu.UseDefaultRadiusAndThickness = true;
            this.btnmenu.Click += new System.EventHandler(this.btnmenu_Click);
            // 
            // panel3
            // 
            this.panel3.BackColor = System.Drawing.Color.Transparent;
            this.panel3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("panel3.BackgroundImage")));
            this.panel3.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.panel3.BorderRadius = 35;
            this.panel3.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel3.GradientBottomLeft = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(54)))));
            this.panel3.GradientBottomRight = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(54)))));
            this.panel3.GradientTopLeft = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(54)))));
            this.panel3.GradientTopRight = System.Drawing.Color.FromArgb(((int)(((byte)(38)))), ((int)(((byte)(43)))), ((int)(((byte)(54)))));
            this.panel3.Location = new System.Drawing.Point(5, 15);
            this.panel3.Name = "panel3";
            this.panel3.Quality = 10;
            this.panel3.Size = new System.Drawing.Size(180, 87);
            this.panel3.TabIndex = 4;
            // 
            // panel2
            // 
            this.panel2.BackColor = System.Drawing.Color.Transparent;
            this.panel2.Dock = System.Windows.Forms.DockStyle.Left;
            this.panel2.Location = new System.Drawing.Point(0, 50);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(255, 505);
            this.panel2.TabIndex = 2;
            // 
            // paneldesktop
            // 
            this.paneldesktop.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.paneldesktop.Location = new System.Drawing.Point(255, 111);
            this.paneldesktop.Name = "paneldesktop";
            this.paneldesktop.Size = new System.Drawing.Size(945, 444);
            this.paneldesktop.TabIndex = 5;
            // 
            // panel4
            // 
            this.panel4.BackColor = System.Drawing.Color.Transparent;
            this.panel4.Controls.Add(this.descriptionpage);
            this.panel4.Controls.Add(this.tittlepage);
            this.panel4.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel4.Location = new System.Drawing.Point(255, 50);
            this.panel4.Name = "panel4";
            this.panel4.Size = new System.Drawing.Size(945, 62);
            this.panel4.TabIndex = 0;
            // 
            // descriptionpage
            // 
            this.descriptionpage.AutoSize = true;
            this.descriptionpage.Font = new System.Drawing.Font("Century Gothic", 9.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.descriptionpage.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(154)))), ((int)(((byte)(154)))), ((int)(((byte)(154)))));
            this.descriptionpage.Location = new System.Drawing.Point(17, 39);
            this.descriptionpage.Name = "descriptionpage";
            this.descriptionpage.Size = new System.Drawing.Size(28, 16);
            this.descriptionpage.TabIndex = 5;
            this.descriptionpage.Text = "???";
            // 
            // tittlepage
            // 
            this.tittlepage.AutoSize = true;
            this.tittlepage.Font = new System.Drawing.Font("Century Gothic", 15.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tittlepage.Location = new System.Drawing.Point(15, 14);
            this.tittlepage.Name = "tittlepage";
            this.tittlepage.Size = new System.Drawing.Size(48, 25);
            this.tittlepage.TabIndex = 5;
            this.tittlepage.Text = "???";
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1200, 555);
            this.Controls.Add(this.panelfecha);
            this.Controls.Add(this.paneluser);
            this.Controls.Add(this.panel4);
            this.Controls.Add(this.paneldesktop);
            this.Controls.Add(this.panelmenu);
            this.Controls.Add(this.panel2);
            this.Controls.Add(this.panel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "Form1";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Form1";
            this.Load += new System.EventHandler(this.Form1_Load);
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            this.paneluser.ResumeLayout(false);
            this.paneluser.PerformLayout();
            this.panelfecha.ResumeLayout(false);
            this.panelfecha.PerformLayout();
            this.panelmenu.ResumeLayout(false);
            this.panel4.ResumeLayout(false);
            this.panel4.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuFormControlBox bunifuFormControlBox1;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox2;
        private System.Windows.Forms.Label labeluser;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
        private Bunifu.UI.WinForms.BunifuGradientPanel paneluser;
        private Bunifu.UI.WinForms.BunifuGradientPanel panelfecha;
        private System.Windows.Forms.Label labelhora;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label fecha;
        private Bunifu.UI.WinForms.BunifuGradientPanel panelmenu;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btncerrar;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnsettings;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnfacturacion;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnreservaciones;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnhabitaciones;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnclientes;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btninicio;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 btnmenu;
        private Bunifu.UI.WinForms.BunifuGradientPanel panel3;
        private System.Windows.Forms.Panel panel2;
        private System.Windows.Forms.Panel paneldesktop;
        private System.Windows.Forms.Panel panel4;
        private System.Windows.Forms.Label label2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton2 bunifuButton21;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label descriptionpage;
        private System.Windows.Forms.Label tittlepage;
    }
}

